services:
  postgres:
      image: postgres:15-alpine
      ports:
        - 5432:5432  # enables connecting locally via psql
      environment:
        POSTGRES_DB: disenio
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin